version: 0.0
os: linux
files:
  - source: /scripts
    destination: /home/ubuntu/
hooks:
  BeforeInstall:
    - location: scripts/start_server.sh
      timeout: 200
      runas: root
  ApplicationStop:
    - location: scripts/cleanup.sh
      timeout: 200
      runas: root
      